# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinnedmessages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='userDp',
        ),
    ]
